"use client";
import { useState } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from 'next/link'
import { motion } from "framer-motion"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [toggle, setToggle] = useState<boolean>(false);
  return (
    <html lang="en">
      <body>
        <header className="w-full h-[50px] bg-[#20202057] flex justify-between  items-center">
         <div className="h-auto w-auto ml-2">
          <Image src="/logo.png" width={46} height={38} alt="" className=""/>
         </div> 
          <Image onClick={()=>{
             setToggle(!toggle)
             
          }} src="/Menu_Mob_.png" width={46} height={38} alt="" className="cursor-pointer md:hidden "/>
          <motion.div
          animate={{ y: 100 }}
          transition={{ delay: 2 }}
          className={` ${toggle? " flex " : " hidden " } absolute flex-col w-[130px] h-[160px] top-0 right-[calc(50%)] bg-[#080808d7] space-y-2 items-center md:hidden `}>
          <Link  href="">ACCUEIL</Link>
          <Link  href="">A PROPOS</Link>
          <Link  href="">ACTIVITÉES</Link>
          <Link  href="">GALERIE</Link>
          <Link  href="">CONTACT</Link>

          </motion.div>
        </header>
        {children}
        <footer>

        </footer>
      </body>
    </html>
  );
}
